### ISSUE TITLE
Toxblade missing a ManeuverDef

### ISSUE THREAD

**Issue by SamaelGray** [Vanilla-Expanded/VanillaFactionsExpanded-Empire#3]
The new melee capacities added for the Toxblades are missing a ManeuverDef that all melee capacities require to register ingame, a simple ToolCapacityDef does not suffice.
An example of a ManeuverDef for vanilla tools:
![image](https://user-images.githubusercontent.com/56392968/226553105-0db900a3-e512-4111-aeeb-1afecb76facb.png)

Toxblade lacking the ManeuverDef with only the handle tool proccing:
![image](https://user-images.githubusercontent.com/56392968/226553348-73ed9905-8e5b-41de-8b03-fefd324dbab4.png)
![image](https://user-images.githubusercontent.com/56392968/226553414-a8187887-89c0-4162-879a-75c6923c0ba4.png)

ManeuverDef added:
![image](https://user-images.githubusercontent.com/56392968/226553440-adf11869-dc1a-45aa-9797-2c7d25af2306.png)

**Comment by legodude17** [comment]
Fixed in [35dc2c](https://github.com/Vanilla-Expanded/VanillaFactionsExpanded-Empire/commit/35dc2c71d88ecece8acb4537cd9d48d156e64b6b).
