### ISSUE TITLE
XML Tree problem

### ISSUE THREAD

**Issue by masakitenchi** [Vanilla-Expanded/VanillaFactionsExpanded-Empire#7]
![image](https://github.com/Vanilla-Expanded/VanillaFactionsExpanded-Empire/assets/11086210/135b1f4e-13dc-479a-ae5e-bcfcfb96715e)

Strange enough that the game doesn't ever error

**Comment by masakitenchi** [comment]
![image](https://github.com/Vanilla-Expanded/VanillaFactionsExpanded-Empire/assets/11086210/ef99330f-7930-44fa-b9e1-4212d8e1e1d4)

Rocketman's Unified_Original.xml shows totally messed xml tree

**Comment by legodude17** [comment]
I'd imagine the game's xml parser ignores it because it's an end comment, but Rocketman's serializer doesn't handle it correctly.
