### ISSUE TITLE
Empire faction leader and questgivers not in court hierarchy

### ISSUE THREAD

**Issue by Aussiemon** [Vanilla-Expanded/VanillaFactionsExpanded-Empire#9]
The High Stellarch is not among the high stellarchs of the great hierarchy:

![image](https://github.com/Vanilla-Expanded/VanillaFactionsExpanded-Empire/assets/13663574/cc275b58-fb9f-454c-ba44-675f9b4acee3)

![image](https://github.com/Vanilla-Expanded/VanillaFactionsExpanded-Empire/assets/13663574/bbf0cde8-e36c-453c-84b9-216938f345b8)

I don't see them in any lower role either.

**Comment by Aussiemon** [comment]
Similarly, this quest-giving high stellarch isn't in the hierarchy:
![image](https://github.com/Vanilla-Expanded/VanillaFactionsExpanded-Empire/assets/13663574/8b742e4d-8c5d-4f7a-8ce2-920bb6d7b312)

**Comment by legodude17** [comment]
Intended. Not every noble is in the Hierarchy, it'd get way too big otherwise.
